#!/usr/bin/env bash
set -eu

export BSYS6="$(dirname $(readlink -f "$0"))/src"

source $BSYS6/exports/vars.sh
source $BSYS6/exports/target.sh

set +u

docker run --rm -it -v "$BSYS6/..":"/bsys6" -v "$WORKDIR":"/root/.local/share/bsys6/work" -e TARGET="$TARGET" -e ARCH="$ARCH" -e VERSION="$VERSION" "registry.gitlab.com/librewolf-community/browser/bsys6/$TARGET" ./bsys6 $@
