when:
  event: manual

matrix:
  ARCH:
    - x86_64
    - i686

steps:
  windows:
    image: registry.gitlab.com/librewolf-community/browser/bsys6/windows:latest
    commands:
      - TARGET=windows ./bsys6 package setup msix portable nupkg
